### ISSUE TITLE
Look into an xcodeproject generator

### ISSUE THREAD

**Issue by orta** [danger/danger-swift#10]
You won't be able to see the autocomplete for Danger without some work, because like with SwiftPM, we inject a target in via paths. This means we need to do this work:

![screen shot 2017-08-26 at 13 49 13](https://user-images.githubusercontent.com/49038/29743730-6c609308-8a65-11e7-842e-6fcaa6bc1f51.png)

With the paths from the build. 

These could be throwaway Xcodeprojects, you could do something like `danger-swift edit` and it generates an xcodeproj in `~/tmp` which references your `Dangerfile.swift` and the custom swift flags.

**Comment by kdawgwilk** [comment]
Or maybe a setup command from the runner that uses this: https://github.com/swift-xcode/xcodeproj to add these flags?

**Comment by orta** [comment]
We probably shouldn't be manipulating existing Xcode projects for it (we'd have to add a new target to it, or have every target in the project dynamically injecting Danger into it ) marathon has the concept of a edit command that covers this quite well ( I wonder if that could be re-used )

**Comment by orta** [comment]
Moving to #35 which has a direct route for doing this
