### ISSUE TITLE
Make CI run on Linux

### ISSUE THREAD

**Issue by orta** [danger/danger-swift#20]
See https://swiftenv.fuller.li/en/latest/installation.html

**Comment by ditansu** [comment]
@orta is it possible to run a danger-swift on Linux?

**Comment by orta** [comment]
Yep, _our_ CI for this repo is running it on linux. 

There isn't really a distribution method right now though, so you will need to either check out using [linux brew](https://twitter.com/Linuxbrew) or do a manual clone + `make install` then it should be availble

**Comment by orta** [comment]
This is now happening
