### ISSUE TITLE
Create an Xcodeproject for editing a Dangerfile in Xcode

### ISSUE THREAD

**Issue by orta** [danger/danger-swift#35]
To run `danger-swift edit` we can demand that to use the feature, mint must be installed - then can be mint's job to download and [run XcodeGen](https://github.com/yonaskolb/XcodeGen) and all danger-swift has to do is create the right project JSON file.

**Comment by orta** [comment]
This is in, though the output is not particularly elegant.

**Comment by pepibumur** [comment]
@orta I just implemented a similar action [here](https://github.com/xcodeswift/sake/blob/master/Sources/SakeKit/GenerateProject.swift). I thought it might be useful to add project generation to Danger.

**Comment by orta** [comment]
Nice - thanks!

**Comment by orta** [comment]
This is in
