### ISSUE TITLE
Install Danger-Swift always requires the latest Xcode version.

### ISSUE THREAD

**Issue by mayoralito** [danger/danger-swift#41]
Hi, 

I'm trying to test `danger-swift` in one of my projects. The project is running on Mac High Sierra 10.13.1 and the Xcode 8.3.3. 

When I try to execute:
```
brew install danger/tap/danger-swift
```

I'm getting this error:
```
Error: Your Xcode (8.3.3) is too outdated.
Please update to Xcode 9.1 (or delete it).
Xcode can be updated from the App Store.
```

Even when the message is clear, I don't understand why danger-swift is not allowing user to use it if they're not using latest Xcode version. 
Is it something related to Swift 4? Why can't be used with Xcode 8.3.3 or lower?

Any clarification on this one will be appreciated. Thanks! 🎄

**Comment by orta** [comment]
I don't have the time and patience to support multiple versions of Swift, that's all. So I opted for Swift 4.0, and used 4.0+ features which means this wouldn't compile. 

That said, the error you're seeing is from Homebrew ( not actually from [Danger Swift's formula](https://github.com/danger/homebrew-tap/blob/master/danger-swift.rb) ) so to use `brew install [anything]` you'd need to update to Xcode 9

**Comment by mayoralito** [comment]
Alright, I was trying to understand the reason. Not asking for you to maintain multiple versions. Just asking for the reason since I got the reason, i will say: Thank you for your time.

**Comment by orta** [comment]
You're welcome 👍
