### ISSUE TITLE
Bad JSON input to danger-swift (possibly due to Github API change?)

### ISSUE THREAD

**Issue by hirad** [danger/danger-swift#52]
Starting today, I noticed that Danger is failing on all our PRs. It turned out to be an issue with parsing the JSON input to `danger-swift`:

```
Failed to parse JSON:
keyNotFound(Danger.DangerDSL.(CodingKeys in _125A41DBF2E88FF661E0539497E789E1).git, Swift.DecodingError.Context(codingPath: [Danger.DSL.(CodingKeys in _125A41DBF2E88FF661E0539497E789E1).danger], debugDescription: "No value associated with key git (\"git\").", underlyingError: nil))
```

When I ran Danger locally (using `danger pr https://github.com/path/to/pr --json`), I saw that the generated JSON had two initial `danger` keys:

```
{
  "danger": {
    "danger": {
      "git": { ... }
    }
  }
}
```

If I edit that file and remove one of the `danger` keys, then we get further but not by much:

```
Failed to parse JSON:
typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [Danger.DSL.(CodingKeys in _125A41DBF2E88FF661E0539497E789E1).danger, Danger.DangerDSL.(CodingKeys in _125A41DBF2E88FF661E0539497E789E1).github, Danger.GitHub.CodingKeys.requestedReviewers], debugDescription: "Expected to decode Array<Any> but found a dictionary instead.", underlyingError: nil))
```

This last issue seems to be related to [this breaking change](https://developer.github.com/changes/2018-01-24-end-thor-preview/) in the Github API. I'll be happy to open a PR for this to address, but at the moment, I'm not sure what the first problem is about. Some guidance on debugging it further would be appreciated :) 

Edit: the double-`danger` key seems to be an issue with running it locally. I just verified that that doesn't seem to occur on CI. On CI I'm only seeing the `requestedReviewers` issue. I'll try to spend some time on that this week.

**Comment by orta** [comment]
Yeah, this whole double danger thing is still a little bit confusing to me - WRT the API thing, yeah, we'll have to change the types and ship a new release of danger-swift

**Comment by orta** [comment]
This is fixed 👍
