### ISSUE TITLE
Danger Swift will need to handle a danger.github which is null

### ISSUE THREAD

**Issue by orta** [danger/danger-swift#59]
The DSL is going to  be extended with an upcoming release today. Is there a way that Danger Swift can _not_ break if an attribute is added to the JSON? I'm pretty sure every time a new attribute was added this needed to change.

**Comment by sunshinejr** [comment]
@orta pretty sure you just need to add `CodingKeys` enum to specify which properties you want. Which would be adding [here](https://github.com/danger/danger-swift/blob/master/Sources/Danger/DangerDSL.swift#L12):
```swift
private enum CodingKeys: String, CodingKey {
    case git
    case github
}
```

**Comment by orta** [comment]
I'm more interested in forward compatibility, when `bitbucket_server` appears in the JSON (which is will now) would that break the JSON parser?

**Comment by SD10** [comment]
It will only break the existing parser if you’re changed the order of the `git` and `github` nodes as well. If `bitbucket` is under the root node, this shouldn’t change anything. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
> The JSON decoder ignores any keys that are not properties of the object it is decoding.

Ah that's great.

Separately, yes, `danger.github` is now optional. In Danger JS' types, I declare both `danger.github` and `danger.bitbucket_server` as non-optional, but I don't think you can get away with that in Swift, which will require an update to all Dangerfiles :(

**Comment by SD10** [comment]
Yeah updating all Dangerfiles can be tricky especially if users aren't using an IDE for compile time warnings.

 I wonder if we can make `danger.github` and `danger.bitbucket_server` implicitly unwrapped optionals. I'm pretty sure you can put `nil` in an `IUO` so decoding should work? The API is definitely less safe but if you're accessing BitBucket information and your repo is hosted on GitHub then this is a programmer error 🤔

**Comment by orta** [comment]
That could probably work, yeah 👍

**Comment by orta** [comment]
Fixed
