### ISSUE TITLE
Is it possible to use danger-swift without a CI setup?

### ISSUE THREAD

**Issue by agisilaos** [danger/danger-swift#60]
Hello you lovely people at Danger,

I would like to ask if it's possible to add/use Danger-Swift into a project when there is no CI set up. On a project that I'm currently working on we don't have any tests(planning to write them soon though) so we didn't configure any CI. On the other hand though it would be awesome to use Danger-Swift on the project because it will help us tremendously with our Code Reviews. Is it possible to use Danger-swift without any CI setup?

Thank you for creating such an awesome project @orta, and sorry if my question is "dumb" or If I didn't understand something correctly.

**Comment by orta** [comment]
Hrm, so it's now possible to do that with Danger JS via `danger local`, so it'd be possible to do it with `danger swift` by adding a process arg to `danger local` so that it runs in Danger Swift instead IMO

**Comment by agisilaos** [comment]
Thank you @orta, for some weird reason I didn't get a notification for this convo 😱 Closing this issue rn.
