### ISSUE TITLE
Somehow Danger JS doesn't get the payload from Danger Swift

### ISSUE THREAD

**Issue by sunshinejr** [danger/danger-swift#69]
[Dangerfile](https://github.com/radex/SwiftyUserDefaults/pull/155/files#diff-76af416a19a7ef774f3bdd60f463d0a5)

I tried to dig but I couldn't figure it out by looking at it, but basically, Danger-Swift says it sends the payload:
```json
Sending results back to Danger
{
  "messages" : [
  ],
  "markdowns" : [
    {
      "message" : "### SwiftLint found issues\n\n| Severity | File | Reason |\n| -------- | ---- | ------ |\nWarning | TestHelper.swift:5 | Prefer `-> Void` over `-> ()`. |\nWarning | TestHelper.swift:9 | Prefer `-> Void` over `-> ()`. |\nWarning | TestHelper.swift:13 | Prefer `-> Void` over `-> ()`. |"
    }
  ],
  "fails" : [
  ],
  "warnings" : [
    {
      "message" : "Big PR, try to keep changes smaller if you can"
    },
    {
      "message" : " Any changes to library code should be reflected in the Changelog."
    },
    {
      "message" : "PR is classed as Work in Progress"
    },
    {
      "message" : "Only one of either the podspec or SPM package was changed. This might be unintentional – double check."
    }
  ]
}
```

And Danger-JS says that there is no valid payload 😅:
```
Error:  Error: Results passed to Danger JS did not include fails.
{}
```

This is a fresh install of Danger & Danger-JS on travis:
```
  - npm install -g danger
  - brew install danger/tap/danger-swift
```

**Comment by behdad-keynejad** [comment]
I'm having the same issue.
It's weird, because danger-js is expecting fails. I added an intentional fail to Dangerfile.swift and now it is working. It sends comments to the PR with the fail message. 
@orta Any comments?

**Comment by orta** [comment]
Yeah this is a known issue in danger js, haven’t figured it out yet

**Comment by orta** [comment]
I got a fix for this coming out with the next major release of dangerjs

**Comment by behdaad** [comment]
@orta Great to hear, I was suspecting DangerSwift wasn't being maintained anymore. It's a privilege having you in the community.
