### ISSUE TITLE
Test with marathon

### ISSUE THREAD

**Issue by orta** [danger/danger-swift#8]
I want the install process for CI to look something like:

```sh
npm install danger
brew install marathon-cli
marathon install danger/danger-swift
```

Then it's ran something like:
```sh
danger process "danger-swift"
```

( or `danger-swift pr` could call `danger process` - that's bit meta though)

Explore what needs to be done to make this work.

**Comment by orta** [comment]
My homebrew PR for marathon is now green, so this is moving forwards 👍 

https://github.com/Homebrew/homebrew-core/pull/17266

**Comment by orta** [comment]
Going to use homebrew tap for now for mac people for now, this isn't great because it doesn't seem to reliably run on Lunix

**Comment by JohnSundell** [comment]
@orta Hey 👋 I'm a bit sad that I've been completely disconnected from this for a while (because I'm very excited about it!). I've got my hands full with some other projects at the moment, but would love to help out fixing the last issues to enable Danger-Swift to be installed through Marathon as soon as possible 👍

**Comment by orta** [comment]
So there'd need to be two things:

* Installation of the binary
* Installation of the lib

Marathon would need to support the [installation](https://github.com/danger/danger-swift/blob/master/Makefile#L12-L16) of [both products](https://github.com/danger/danger-swift/blob/master/Package.swift#L9-L12) from the Package.swift, ideally into `/usr/local/bin` and `/usr/local/lib/danger/*`. I tried to get the `bin` one working in https://github.com/JohnSundell/Marathon/pull/127 but not liub

**Comment by orta** [comment]
I'm calling this as something that is just not really how things get done from my perspective, marathon provides a tonne of runtime value for danger-swift - but I'd rather rely on brew/docker or maybe Swift PM for installation if it ever becomes popular.
