### ISSUE TITLE
Interface with GitHub Review API

### ISSUE THREAD

**Issue by yhkaplan** [danger/danger-swift#82]
I currently use Danger at work to request reviews from other team members automatically if there are fewer than two reviewers for a pull request. It would be nice if Danger-swift could do this as well. 

I’ll write up an example of how it might look in a Dangerfile when I’m not on my phone.

**Comment by SD10** [comment]
Hey @yhkaplan, I believe this is a duplicate of #17

**Comment by yhkaplan** [comment]
Hmm, definitely a duplicate if the timing of #17 is near... I'll close this for now.

**Comment by bitomule** [comment]
Hi @yhkaplan , where you able to request reviews after github api integration? Can't find the option inside api. Thanks!
