### ISSUE TITLE
Error while trying to install danger-swift

### ISSUE THREAD

**Issue by agisilaos** [danger/danger-swift#85]
Hello, recently I clean-installed my mbp and installed macOS mojave. Now I'm trying to install danger-swift but I'm getting the error below. Not sure what I may do wrong here so any help/tips is beyond appreciated. 

<img width="1389" alt="screenshot 2018-10-10 at 13 43 42" src="https://user-images.githubusercontent.com/10944108/46731106-898fe300-cc92-11e8-8705-bb619a4ed6b3.png">

**Comment by orta** [comment]
Looks like there's something not quite set up with your Xcode paths at a guess

**Comment by agisilaos** [comment]
Thank you @orta! You're right. So here's how I fixed it. I will post it here as a reference for people that may encounter the same issue. 

1. Check the current SDK path
```bash
xcrun --show-sdk-path --sdk macosx
```

2. Switch the default SDK location by invoking:
```bash
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```
